import os
import sys
import json
import os
import pychrome
# from dragTool import Toolbox 

import time
from difflib import SequenceMatcher
import time

_file_ = os.path.abspath(__file__)

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(_file_), '..')))
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(_file_), '../..')))
from tools.dragTool import Toolbox 
from dotenv import load_dotenv

load_dotenv()
from tools.browserUseClient import send_task

# assuming your dragTool.py defines a class

# Instantiate your drag tool
drag_tool = Toolbox()

ELEMENTS = os.getenv("ELEMENTS_DESCRIPTION_JSON_PATH")


with open(ELEMENTS, 'r') as f:
    category_data = json.load(f)

class Executor:


    def __init__(self, debug_port=9222, tab_index=0):
        self.debug_port = debug_port
        self.browser = pychrome.Browser(url=f"http://127.0.0.1:{self.debug_port}")
        self.tab = self.browser.list_tab()[tab_index]
        self.tab.start()


    @staticmethod
    def clean_workspace():
        """
        Clean the workspace by dragging all used blocks back to the palette.
        Uses get_list_of_used_blocks() to find blocks and their coordinates.
        """
        from tools.filter import find_used_blocks
        
        print("🧹 Cleaning workspace...")
        
        # Get all blocks currently in workspace
        used_blocks = find_used_blocks()
        
        if not used_blocks or len(used_blocks) == 0:
            print("✓ Workspace is already empty")
            return True
        
        print(f"Found {len(used_blocks)} blocks to remove")
        
        # Drag each block back to the palette (reverse operation)
        for i, block in enumerate(used_blocks, 1):
            try:
                # Current position in workspace
                x_current = block["x"]
                y_current = block["y"]
                
                # Target position (back to palette area - left side of screen)
                # We drag them to a safe area outside the workspace
                x_target = 100  # Left side (palette area)
                y_target = 300  # Middle height
                
                print(f"  Removing block {i}/{len(used_blocks)}: '{block['text_content']}'")
                print(f"    From workspace ({x_current}, {y_current}) → To palette ({x_target}, {y_target})")
                
                # Perform reverse drag
                drag_tool.drag_and_drop(
                    x_start=x_current,
                    y_start=y_current,
                    x_end=x_target,
                    y_end=y_target
                )
                
                time.sleep(0.3)  # Small delay between removals
                
            except Exception as e:
                print(f"  ⚠ Error removing block: {e}")
                continue
        
        print("✓ Workspace cleaned successfully")
        return True
    @staticmethod
    def find_closest_block(category: str, block_query: str) -> dict:
        """
        Find the closest matching block in description.json using fuzzy matching
        """
        description_path = os.getenv("ELEMENTS_DESCRIPTION_JSON_PATH")
        try:
            with open(description_path, 'r') as f:
                descriptions = json.load(f)
            
            if category in descriptions:
                best_match = None
                highest_ratio = 0
                
                # Search through all blocks in the category
                for block in descriptions[category]["blocks"]:
                    ratio = SequenceMatcher(
                        None, block["name"].lower(), block_query.lower()
                    ).ratio()
                    
                    if ratio > highest_ratio and ratio > 0.6:
                        highest_ratio = ratio
                        best_match = block
                
                if best_match:
                    coords = best_match["coordinates"]
                    x = float(coords.split("x: ")[1].split(",")[0])
                    y = float(coords.split("y: ")[1])
                    
                    return {
                        "name": best_match["name"],
                        "description": best_match["description"],
                        "coordinates": {"x": x, "y": y},
                        "match_confidence": highest_ratio
                    }
                    
        except Exception as e:
            print(f"Error finding block: {e}")
        return None  

    @staticmethod
    def executor_tool(json_plan: str, delay=0.5):
        """
        Executes a sequence of block manipulation commands generated by an agent.

        Arguments:
            - json_plan (str): A JSON string containing a list of steps to execute.
              Each step should specify:
            - step (int): The step number in the sequence.
            - category (str): The block category (e.g., "Events", "Control").
            - block (str): The name of the block to interact with.

        Example json_plan:
        {
          "steps": [
            {
              "step": 1,
              "category": "Events",
              "block": "when green flag clicked"
            },
            {
              "step": 2,
              "category": "Control",
              "block": "forever"
            }
          ]
        }

        The function locates each block by fuzzy matching, clicks the category tab,
        and performs drag-and-drop actions to build the desired program structure.
        """

         # Parse the JSON plan
        try:
            plan = json.loads(json_plan)
        except json.JSONDecodeError as e:
            print("Invalid JSON plan:", e)
            return "❌ Invalid JSON plan."
        
        steps = plan.get("steps", [])
        print(f"Executing {len(steps)} steps...")
        scroll = False
        blockno = 1
        for step in steps:
            print(f"\nProcessing step: {step}")
            step_num = step["step"]
            category = step["category"]
            block = step["block"]



            # print(f"\nExecuting Step {step_num}: {category} → {block}")

            # 1. Find block in description.json
            match = Executor.find_closest_block(category, block)
            if not match:
                print(f"❌ Could not find block '{block}' in category '{category}'")           
                continue
            
            start = match["coordinates"]
            x_start, y_start = start["x"], start["y"]
            

            # scroll to the block position if needed
       
                


            # 2. Compute end position
            x_end = 350
            y_end = 140 + 37 * (blockno - 1)
            blockno += 1
            print(f"  Start position: ({x_start}, {y_start})")
            print(f"  End position:   ({x_end}, {y_end})")

            # 3. Click category tab first (if needed)
            category_position = category_data.get(category, {}).get("coordinates", "x: 0, y: 0")
            category_x, category_y = map(int, category_position.replace("x: ", "").replace("y: ", "").split(", "))
            drag_tool.click(category_x, category_y + 5)

            time.sleep(delay)
            if y_start > 700:
                scroll = True
                drag_tool.scroll( delta_y=405)
                
                y_start -= 405
            
            if y_end > 700:
                scroll = True
                drag_tool.scroll( x=574, delta_y=405)
                
                y_end -= 405

            # 4. Drag and drop the block
            drag_tool.drag_and_drop(
                x_start=x_start, 
                y_start=y_start, 
                x_end=x_end, 
                y_end=y_end
            )
            if scroll:
                time.sleep(1)
            scroll = False
        return "✅ Execution completed."

    @staticmethod
    def clean_and_execute_tool(json_plan: str, delay=0.5):
        """
        NEW TOOL: Cleans workspace first, then executes the new block sequence.
        This is specifically for CODE FIXING operations.
        
        Steps:
        1. Get all blocks currently in workspace using get_list_of_used_blocks()
        2. Drag each block FROM workspace coordinates BACK to palette (reverse drag)
        3. Execute the new correct sequence of blocks
        
        Arguments:
            - json_plan (str): JSON string with steps to execute
            - delay (float): Delay between operations
            
        Returns:
            str: Success or error message
        """
        print("\n" + "="*60)
        print("🔧 CLEAN & EXECUTE TOOL")
        print("="*60)
        
        # STEP 1: Clean the workspace
        print("\n[STEP 1] Cleaning existing workspace...")
        try:
            Executor.clean_workspace()
            time.sleep(1)  # Wait for cleanup to complete
        except Exception as e:
            print(f"⚠ Error during cleanup: {e}")
            print("Continuing with execution anyway...")
        
        # STEP 2: Refresh to update DOM
        print("\n[STEP 2] Refreshing workspace state...")
        try:
            send_task("refresh")
            time.sleep(2)
        except Exception as e:
            print(f"⚠ Error refreshing: {e}")
        
        # STEP 3: Execute new blocks
        print("\n[STEP 3] Executing new block sequence...")
        result = Executor.executor_tool(json_plan, delay)
        
        print("\n" + "="*60)
        print("✅ CLEAN & EXECUTE COMPLETED")
        print("="*60)
        
        return result

# if __name__ == "__main__":
#     # Example JSON plan
#     test_json_plan = json.dumps({
#   "steps": [
#     {
#       "step": 1,
#       "category": "Looks",
#       "block": "Hide"
#     },
#     {
#       "step": 2,
#       "category": "Looks",
#       "block": "show"
#     },
#     {
#       "step": 3,
#       "category": "Motion",
#       "block": "go to random position"
#     }
#   ]
# })

#     # Call the executor_tool function with the test JSON plan
# Executor.executor_tool(test_json_plan)

