import os
import sys
import json
import os
import pychrome
# from dragTool import Toolbox 

import time
from difflib import SequenceMatcher
import time

_file_ = os.path.abspath(__file__)

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(_file_), '..')))
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(_file_), '../..')))
from tools.dragTool import Toolbox 
from dotenv import load_dotenv

load_dotenv()
from tools.browserUseClient import send_task

# assuming your dragTool.py defines a class

# Instantiate your drag tool
drag_tool = Toolbox()

ELEMENTS = os.getenv("ELEMENTS_DESCRIPTION_JSON_PATH")


with open(ELEMENTS, 'r') as f:
    category_data = json.load(f)

class Executor:


    def __init__(self, debug_port=9222, tab_index=0):
        self.debug_port = debug_port
        self.browser = pychrome.Browser(url=f"http://127.0.0.1:{self.debug_port}")
        self.tab = self.browser.list_tab()[tab_index]
        self.tab.start()

    @staticmethod
    def find_closest_block(category: str, block_query: str) -> dict:
        """
        Find the closest matching block in description.json using fuzzy matching
        """
        description_path = os.getenv("ELEMENTS_DESCRIPTION_JSON_PATH")
        try:
            with open(description_path, 'r') as f:
                descriptions = json.load(f)
            
            if category in descriptions:
                best_match = None
                highest_ratio = 0
                
                # Search through all blocks in the category
                for block in descriptions[category]["blocks"]:
                    ratio = SequenceMatcher(
                        None, block["name"].lower(), block_query.lower()
                    ).ratio()
                    
                    if ratio > highest_ratio and ratio > 0.6:
                        highest_ratio = ratio
                        best_match = block
                
                if best_match:
                    coords = best_match["coordinates"]
                    x = float(coords.split("x: ")[1].split(",")[0])
                    y = float(coords.split("y: ")[1])
                    
                    return {
                        "name": best_match["name"],
                        "description": best_match["description"],
                        "coordinates": {"x": x, "y": y},
                        "match_confidence": highest_ratio
                    }
                    
        except Exception as e:
            print(f"Error finding block: {e}")
        return None  

    @staticmethod
    def executor_tool(json_plan: str, delay=0.5):
        """
        Executes a sequence of block manipulation commands generated by an agent.

        Arguments:
            - json_plan (str): A JSON string containing a list of steps to execute.
              Each step should specify:
            - step (int): The step number in the sequence.
            - category (str): The block category (e.g., "Events", "Control").
            - block (str): The name of the block to interact with.

        Example json_plan:
        {
          "steps": [
            {
              "step": 1,
              "category": "Events",
              "block": "when green flag clicked"
            },
            {
              "step": 2,
              "category": "Control",
              "block": "forever"
            }
          ]
        }

        The function locates each block by fuzzy matching, clicks the category tab,
        and performs drag-and-drop actions to build the desired program structure.
        """

         # Parse the JSON plan
        try:
            plan = json.loads(json_plan)
        except json.JSONDecodeError as e:
            print("Invalid JSON plan:", e)
            return "❌ Invalid JSON plan."
        
        steps = plan.get("steps", [])
        print(f"Executing {len(steps)} steps...")
        scroll = False
        blockno = 1
        for step in steps:
            print(f"\nProcessing step: {step}")
            step_num = step["step"]
            category = step["category"]
            block = step["block"]



            # print(f"\nExecuting Step {step_num}: {category} → {block}")

            # 1. Find block in description.json
            match = Executor.find_closest_block(category, block)
            if not match:
                print(f"❌ Could not find block '{block}' in category '{category}'")           
                continue
            
            start = match["coordinates"]
            x_start, y_start = start["x"], start["y"]
            

            # scroll to the block position if needed
       
                


            # 2. Compute end position
            x_end = 350
            y_end = 140 + 33 * (blockno - 1)
            blockno += 1
            print(f"  Start position: ({x_start}, {y_start})")
            print(f"  End position:   ({x_end}, {y_end})")

            # 3. Click category tab first (if needed)
            category_position = category_data.get(category, {}).get("coordinates", "x: 0, y: 0")
            category_x, category_y = map(int, category_position.replace("x: ", "").replace("y: ", "").split(", "))
            drag_tool.click(category_x, category_y + 5)

            time.sleep(delay)
            if y_start > 700:
                scroll = True
                drag_tool.scroll( delta_y=405)
                
                y_start -= 405
            
            if y_end > 700:
                scroll = True
                drag_tool.scroll( x=574, delta_y=405)
                
                y_end -= 405

            # 4. Drag and drop the block
            drag_tool.drag_and_drop(
                x_start=x_start, 
                y_start=y_start, 
                x_end=x_end, 
                y_end=y_end
            )
            if scroll:
                time.sleep(1)
            scroll = False
        return "✅ Execution completed."



# if __name__ == "__main__":
#     # Example JSON plan
#     test_json_plan = json.dumps({
#   "steps": [
#     {
#       "step": 1,
#       "category": "Looks",
#       "block": "Hide"
#     },
#     {
#       "step": 2,
#       "category": "Looks",
#       "block": "show"
#     },
#     {
#       "step": 3,
#       "category": "Motion",
#       "block": "go to random position"
#     }
#   ]
# })

#     # Call the executor_tool function with the test JSON plan
# Executor.executor_tool(test_json_plan)

