# import json
# from typing import List, Dict, Any
# from langchain_core.tools import tool
# import os
# import sys

# sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
# sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../..')))


# from tools.execution import Executor

# executor = Executor()

# @tool
# def make_blocks(json_string: str) -> str:
#     """
#         Executes a sequence of block manipulation commands generated by an agent.

#         Arguments:
#             - json_plan (str): A JSON string containing a list of steps to execute.
#               Each step should specify:
#             - step (int): The step number in the sequence.
#             - category (str): The block category (e.g., "Events", "Control").
#             - block (str): The name of the block to interact with.

#         Example json_plan:
#         {
#           "steps": [
#             {
#               "step": 1,
#               "category": "Events",
#               "block": "when green flag clicked"
#             },
#             {
#               "step": 2,
#               "category": "Control",
#               "block": "forever"
#             }
#           ]
#         }

#         The function locates each block by fuzzy matching, clicks the category tab,
#         and performs drag-and-drop actions to build the desired program structure.
#         """
#     if len(json_string.strip()) == 0:
#         print("Empty JSON string provided.")
#         return "false"
#     try:
#         executor.executor_tool(json_string)
#         return "true"
#     except json.JSONDecodeError:
#         print("Invalid JSON format")
#         return "false"


# @tool
# def clean_and_make_blocks(json_string: str) -> str:
#     """
#     Cleans the workspace by removing existing blocks, then executes new block sequence.
#     This tool is specifically for CODE FIXING operations where we need to replace
#     incorrect code with correct code.
    
#     Steps:
#     1. Finds all blocks currently in workspace using get_list_of_used_blocks()
#     2. Drags each block FROM workspace (current coordinates) BACK to palette (reverse drag)
#     3. Executes the new correct sequence of blocks
    
#     Arguments:
#         - json_string (str): A JSON string containing steps to execute
        
#     Example json_string:
#     {
#       "steps": [
#         {"step": 1, "category": "Events", "block": "when green flag clicked"},
#         {"step": 2, "category": "Control", "block": "repeat 10"},
#         {"step": 3, "category": "Looks", "block": "say Meow for 2 seconds"}
#       ]
#     }
    
#     Returns:
#         str: "true" if successful, "false" if error
#     """
#     if len(json_string.strip()) == 0:
#         print("Empty JSON string provided.")
#         return "false"
    
#     try:
#         result = executor.clean_and_execute_tool(json_string)
#         return "true" if "completed" in result.lower() else "false"
#     except json.JSONDecodeError:
#         print("Invalid JSON format")
#         return "false"
#     except Exception as e:
#         print(f"Error in clean_and_make_blocks: {e}")
#         return "false"

import json
from typing import List, Dict, Any
from langchain_core.tools import tool
import os
import sys

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../..')))

from tools.execution import AdvancedExecutor

executor = AdvancedExecutor()

@tool
def make_blocks_advanced(json_string: str) -> str:
    '''
    Execute blocks with ADVANCED NESTING support.
    
    Handles:
    - Blocks inside containers (forever, repeat, if)
    - Condition blocks in diamond/hexagon slots
    - Multi-level nesting
    - Proper coordinate calculation
    
    JSON Format:
    {
      "steps": [
        {"step": 1, "category": "Events", "block": "when green flag clicked", 
         "placement": "root", "parent_step": null},
        {"step": 2, "category": "Control", "block": "forever", 
         "placement": "below", "parent_step": 1},
        {"step": 3, "category": "Control", "block": "if then", 
         "placement": "inside", "parent_step": 2},
        {"step": 4, "category": "Sensing", "block": "touching object", 
         "placement": "condition", "parent_step": 3},
        {"step": 5, "category": "Motion", "block": "move steps", 
         "placement": "inside", "parent_step": 3}
      ]
    }
    '''
    if len(json_string.strip()) == 0:
        print("Empty JSON string provided.")
        return "false"
    
    try:
        result = executor.execute_with_nesting(json_string)
        return "true" if "completed" in result.lower() else "false"
    except json.JSONDecodeError:
        print("Invalid JSON format")
        return "false"
    except Exception as e:
        print(f"Error in make_blocks_advanced: {e}")
        return "false"


@tool
def clean_and_make_blocks_advanced(json_string: str) -> str:
    '''
    Clean workspace then execute with ADVANCED NESTING.
    
    Use for CODE FIXING operations.
    
    Process:
    1. Remove all blocks from workspace
    2. Refresh DOM
    3. Execute new blocks with proper nesting
    '''
    if len(json_string.strip()) == 0:
        print("Empty JSON string provided.")
        return "false"
    
    try:
        result = executor.clean_and_execute(json_string)
        return "true" if "completed" in result.lower() else "false"
    except json.JSONDecodeError:
        print("Invalid JSON format")
        return "false"
    except Exception as e:
        print(f"Error in clean_and_make_blocks_advanced: {e}")
        return "false"